trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: '$(solution)'

# - task: VSBuild@1
#   displayName: 'Build Solution using MSBuild'
#   inputs:
#     solution: '$(solution)'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'
- task: MSBuild@1
  inputs:
    solution: '$(solution)'
    configuration: '$(buildConfiguration)'
    # platform: '$(buildPlatform)'
    clean: true
    restoreNugetPackages: true
    # msbuildArgs: '/p:OutputPath=$(Build.ArtifactStagingDirectory)\bin /p:BaseOutputPath=$(Build.ArtifactStagingDirectory)\bin'  

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
