trigger:
  branches:
    include:
      - main  # Change this to match your default branch

pool:
  vmImage: 'windows-latest'

steps:

  - script: echo Hello from here and there also
    displayName: 'Run a one-line script'
